import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import ts from 'typescript';
const source = readFileSync('client/src/lib/cosmetics-payment-matching.ts', 'utf8');
const compiled = ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.ESNext, target: ts.ScriptTarget.ES2020 } }).outputText;
const { matchingTotals } = await import(`data:text/javascript;base64,${Buffer.from(compiled).toString('base64')}`);
assert.equal(matchingTotals(Array(10).fill('110'), Array(5).fill('220')).eligible, true);
assert.equal(matchingTotals(Array(11).fill('100'), Array(2).fill('550')).eligible, true);
assert.equal(matchingTotals(['0.1','0.2'], ['0.3']).difference, '0.00');
assert.equal(matchingTotals(['101'], ['100']).eligible, true);
assert.equal(matchingTotals(['99'], ['100']).eligible, true);
assert.equal(matchingTotals(['101.0001'], ['100']).eligible, false);
assert.equal(matchingTotals(['98.9999'], ['100']).eligible, false);
assert.equal(matchingTotals([], ['1']).eligible, false);
assert.equal(matchingTotals(['1'], []).eligible, false);
assert.equal(matchingTotals(['999999999999999.99','0.01'], ['1000000000000000']).difference, '0.00');
assert.throws(() => matchingTotals(['NaN'], ['1']));
console.log('Cosmetics matching decimal and many-to-many checks passed');
assert.equal(matchingTotals(['1100'], ['1400', '-200', '-100']).difference, '0.00');
assert.equal(matchingTotals(['1100'], ['1400', '-200', '-100']).eligible, true);
assert.equal(matchingTotals(['100'], ['100', '-200']).eligible, false);
