"""Add hall, counter_group and hall_group_binding tables

Revision ID: 9027644da811
Revises: 861c1ad607a5
Create Date: 2025-09-02 14:18:36.356396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9027644da811'
down_revision: Union[str, Sequence[str], None] = '861c1ad607a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
