CREATE TABLE "activities" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"room_id" varchar,
	"type" text NOT NULL,
	"description" text NOT NULL,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "bills" (
	"bill_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "bills_bill_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"contract_id" integer NOT NULL,
	"bill_period_start" date NOT NULL,
	"bill_period_end" date NOT NULL,
	"total_amount" numeric(12, 2) NOT NULL,
	"status" varchar(20) DEFAULT 'Unpaid' NOT NULL,
	"due_date" date,
	"paid_date" date,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "brands" (
	"brand_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "brands_brand_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"brand_name" varchar(100) NOT NULL,
	"brand_name_en" varchar(100),
	"category" varchar(50),
	"logo_url" varchar(255),
	"description" text,
	"is_active" boolean DEFAULT true,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "contract_spaces" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "contract_spaces_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"contract_id" integer NOT NULL,
	"space_id" integer NOT NULL,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "contracts" (
	"contract_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "contracts_contract_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"contract_code" varchar(100) NOT NULL,
	"tenant_id" integer NOT NULL,
	"brand_id" integer,
	"start_date" date NOT NULL,
	"end_date" date NOT NULL,
	"status" varchar(20) DEFAULT 'Draft' NOT NULL,
	"free_rent_days" integer DEFAULT 0,
	"security_deposit" numeric(12, 2),
	"notes" text,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "contracts_contract_code_unique" UNIQUE("contract_code")
);
--> statement-breakpoint
CREATE TABLE "floor_plans" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"level" text NOT NULL,
	"image_url" text,
	"is_active" boolean DEFAULT true,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "floors" (
	"floor_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "floors_floor_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"floor_name" varchar(50) NOT NULL,
	"display_order" integer DEFAULT 0,
	"description" text,
	"created_at" timestamp DEFAULT now(),
	CONSTRAINT "floors_floor_name_unique" UNIQUE("floor_name")
);
--> statement-breakpoint
CREATE TABLE "hotspots" (
	"hotspot_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "hotspots_hotspot_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"layout_id" integer NOT NULL,
	"space_id" integer NOT NULL,
	"shape_type" varchar(20) DEFAULT 'rect' NOT NULL,
	"coordinates_data" json NOT NULL,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "layouts" (
	"layout_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "layouts_layout_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"floor_id" integer NOT NULL,
	"background_image_url" varchar(255),
	"effective_start_date" date NOT NULL,
	"effective_end_date" date,
	"is_active" boolean DEFAULT true,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "rent_terms" (
	"term_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "rent_terms_term_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"contract_id" integer NOT NULL,
	"term_start_date" date NOT NULL,
	"term_end_date" date NOT NULL,
	"rent_type" varchar(20) NOT NULL,
	"fixed_amount" numeric(12, 2),
	"percentage_rate" numeric(5, 2),
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "role_permissions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "role_permissions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"role_id" integer NOT NULL,
	"permission_code" varchar(50) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "roles" (
	"role_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "roles_role_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"role_name" varchar(50) NOT NULL,
	"description" text,
	"created_at" timestamp DEFAULT now(),
	CONSTRAINT "roles_role_name_unique" UNIQUE("role_name")
);
--> statement-breakpoint
CREATE TABLE "rooms" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"room_number" text NOT NULL,
	"name" text NOT NULL,
	"area" numeric(10, 2) NOT NULL,
	"tenant" text,
	"status" text DEFAULT 'vacant' NOT NULL,
	"monthly_revenue" numeric(12, 2) DEFAULT '0',
	"revenue_per_sqm" numeric(10, 2) DEFAULT '0',
	"lease_expiry" text,
	"contract_type" text,
	"x" numeric(8, 4) NOT NULL,
	"y" numeric(8, 4) NOT NULL,
	"width" numeric(8, 4) NOT NULL,
	"height" numeric(8, 4) NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "rooms_room_number_unique" UNIQUE("room_number")
);
--> statement-breakpoint
CREATE TABLE "space_assets" (
	"space_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "space_assets_space_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"space_code" varchar(50) NOT NULL,
	"floor_id" integer NOT NULL,
	"area" numeric(10, 2) NOT NULL,
	"space_type" varchar(20) DEFAULT 'Leasable' NOT NULL,
	"status" varchar(20) DEFAULT 'Active' NOT NULL,
	"effective_start_date" date NOT NULL,
	"effective_end_date" date,
	"created_at" timestamp DEFAULT now(),
	CONSTRAINT "space_assets_space_code_unique" UNIQUE("space_code")
);
--> statement-breakpoint
CREATE TABLE "space_lineage" (
	"lineage_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "space_lineage_lineage_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"operation_type" varchar(20) NOT NULL,
	"previous_space_id" integer,
	"next_space_id" integer,
	"area_contributed" numeric(10, 2),
	"effective_date" date NOT NULL,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "tenants" (
	"tenant_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tenants_tenant_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"company_name" varchar(255) NOT NULL,
	"tenant_code" varchar(50) NOT NULL,
	"legal_representative" varchar(100),
	"business_license" varchar(100),
	"contact_person" varchar(100),
	"contact_phone" varchar(20),
	"contact_email" varchar(100),
	"address" text,
	"is_active" boolean DEFAULT true,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "tenants_tenant_code_unique" UNIQUE("tenant_code")
);
--> statement-breakpoint
CREATE TABLE "users" (
	"user_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_user_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"username" varchar(50) NOT NULL,
	"password_hash" varchar(255) NOT NULL,
	"full_name" varchar(100) NOT NULL,
	"email" varchar(100) NOT NULL,
	"role_id" integer,
	"is_active" boolean DEFAULT true,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "users_username_unique" UNIQUE("username"),
	CONSTRAINT "users_email_unique" UNIQUE("email")
);
--> statement-breakpoint
ALTER TABLE "activities" ADD CONSTRAINT "activities_room_id_rooms_id_fk" FOREIGN KEY ("room_id") REFERENCES "public"."rooms"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "bills" ADD CONSTRAINT "bills_contract_id_contracts_contract_id_fk" FOREIGN KEY ("contract_id") REFERENCES "public"."contracts"("contract_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "contract_spaces" ADD CONSTRAINT "contract_spaces_contract_id_contracts_contract_id_fk" FOREIGN KEY ("contract_id") REFERENCES "public"."contracts"("contract_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "contract_spaces" ADD CONSTRAINT "contract_spaces_space_id_space_assets_space_id_fk" FOREIGN KEY ("space_id") REFERENCES "public"."space_assets"("space_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "contracts" ADD CONSTRAINT "contracts_tenant_id_tenants_tenant_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("tenant_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "contracts" ADD CONSTRAINT "contracts_brand_id_brands_brand_id_fk" FOREIGN KEY ("brand_id") REFERENCES "public"."brands"("brand_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hotspots" ADD CONSTRAINT "hotspots_layout_id_layouts_layout_id_fk" FOREIGN KEY ("layout_id") REFERENCES "public"."layouts"("layout_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hotspots" ADD CONSTRAINT "hotspots_space_id_space_assets_space_id_fk" FOREIGN KEY ("space_id") REFERENCES "public"."space_assets"("space_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "layouts" ADD CONSTRAINT "layouts_floor_id_floors_floor_id_fk" FOREIGN KEY ("floor_id") REFERENCES "public"."floors"("floor_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rent_terms" ADD CONSTRAINT "rent_terms_contract_id_contracts_contract_id_fk" FOREIGN KEY ("contract_id") REFERENCES "public"."contracts"("contract_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "role_permissions" ADD CONSTRAINT "role_permissions_role_id_roles_role_id_fk" FOREIGN KEY ("role_id") REFERENCES "public"."roles"("role_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "space_assets" ADD CONSTRAINT "space_assets_floor_id_floors_floor_id_fk" FOREIGN KEY ("floor_id") REFERENCES "public"."floors"("floor_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "space_lineage" ADD CONSTRAINT "space_lineage_previous_space_id_space_assets_space_id_fk" FOREIGN KEY ("previous_space_id") REFERENCES "public"."space_assets"("space_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "space_lineage" ADD CONSTRAINT "space_lineage_next_space_id_space_assets_space_id_fk" FOREIGN KEY ("next_space_id") REFERENCES "public"."space_assets"("space_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "users" ADD CONSTRAINT "users_role_id_roles_role_id_fk" FOREIGN KEY ("role_id") REFERENCES "public"."roles"("role_id") ON DELETE no action ON UPDATE no action;