"""add_group_code_to_revenue_data

Revision ID: a5091f7e64c1
Revises: 11e143686da1
Create Date: 2025-09-15 16:31:06.094712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5091f7e64c1'
down_revision: Union[str, Sequence[str], None] = '11e143686da1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_revenue_trends_unique'), table_name='revenue_trends')
    op.drop_index(op.f('ix_revenue_trends_counter_id'), table_name='revenue_trends')
    op.drop_index(op.f('ix_revenue_trends_id'), table_name='revenue_trends')
    op.drop_index(op.f('ix_revenue_trends_trend_date'), table_name='revenue_trends')
    op.drop_table('revenue_trends')
    op.drop_table('BH_DW_TIME_DIM')
    op.drop_table('ODS_SALEGOODSLIST')
    op.drop_index(op.f('idx_revenue_summary_unique'), table_name='revenue_summary')
    op.drop_index(op.f('ix_revenue_summary_floor_id'), table_name='revenue_summary')
    op.drop_index(op.f('ix_revenue_summary_id'), table_name='revenue_summary')
    op.drop_index(op.f('ix_revenue_summary_report_date'), table_name='revenue_summary')
    op.drop_index(op.f('ix_revenue_summary_store_id'), table_name='revenue_summary')
    op.drop_table('revenue_summary')
    op.alter_column('counter_geometries', 'geometry_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='几何信息ID',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('counter_geometries_geometry_id_seq'::regclass)"))
    op.alter_column('counter_geometries', 'position_x',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='X坐标（矩形）',
               existing_nullable=True)
    op.alter_column('counter_geometries', 'position_y',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Y坐标（矩形）',
               existing_nullable=True)
    op.alter_column('counter_geometries', 'width',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='宽度（矩形）',
               existing_nullable=True)
    op.alter_column('counter_geometries', 'height',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='高度（矩形）',
               existing_nullable=True)
    op.alter_column('counter_geometries', 'rotation',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='旋转角度',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('counter_geometries', 'polygon_coordinates',
               existing_type=sa.TEXT(),
               comment='多边形坐标点，JSON格式：[[x1,y1],[x2,y2],...]',
               existing_nullable=True)
    op.alter_column('counter_geometries', 'center_x',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='圆心X坐标',
               existing_nullable=True)
    op.alter_column('counter_geometries', 'center_y',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='圆心Y坐标',
               existing_nullable=True)
    op.alter_column('counter_geometries', 'radius',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='半径',
               existing_nullable=True)
    op.alter_column('counter_geometries', 'ellipse_center_x',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='椭圆中心X坐标',
               existing_nullable=True)
    op.alter_column('counter_geometries', 'ellipse_center_y',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='椭圆中心Y坐标',
               existing_nullable=True)
    op.alter_column('counter_geometries', 'ellipse_radius_x',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='椭圆X轴半径',
               existing_nullable=True)
    op.alter_column('counter_geometries', 'ellipse_radius_y',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='椭圆Y轴半径',
               existing_nullable=True)
    op.alter_column('counter_geometries', 'ellipse_rotation',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='椭圆旋转角度',
               existing_nullable=True)
    op.alter_column('counter_geometries', 'bounding_box_min_x',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='边界框最小X坐标',
               existing_nullable=True)
    op.alter_column('counter_geometries', 'bounding_box_min_y',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='边界框最小Y坐标',
               existing_nullable=True)
    op.alter_column('counter_geometries', 'bounding_box_max_x',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='边界框最大X坐标',
               existing_nullable=True)
    op.alter_column('counter_geometries', 'bounding_box_max_y',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='边界框最大Y坐标',
               existing_nullable=True)
    op.alter_column('counter_geometries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('counter_geometries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='更新时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_counter_geometries_bounding_box'), table_name='counter_geometries')
    op.drop_index(op.f('idx_counter_geometries_counter_id'), table_name='counter_geometries')
    op.drop_index(op.f('idx_counter_geometries_shape_type'), table_name='counter_geometries')
    op.drop_constraint(op.f('unique_counter_geometry'), 'counter_geometries', type_='unique')
    op.create_index(op.f('ix_counter_geometries_geometry_id'), 'counter_geometries', ['geometry_id'], unique=False)
    op.drop_constraint(op.f('counter_geometries_counter_id_fkey'), 'counter_geometries', type_='foreignkey')
    op.create_foreign_key(None, 'counter_geometries', 'counters', ['counter_id'], ['counter_id'])
    op.drop_table_comment(
        'counter_geometries',
        existing_comment='柜位几何信息表',
        schema=None
    )
    op.alter_column('counter_geometry_properties', 'property_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='属性ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('counter_geometry_properties', 'property_name',
               existing_type=sa.VARCHAR(length=50),
               comment='属性名',
               existing_nullable=False)
    op.alter_column('counter_geometry_properties', 'property_value',
               existing_type=sa.TEXT(),
               comment='属性值（JSON格式）',
               existing_nullable=True)
    op.alter_column('counter_geometry_properties', 'property_type',
               existing_type=sa.VARCHAR(length=20),
               comment='属性类型：string, number, boolean, json',
               existing_nullable=True,
               existing_server_default=sa.text("'string'::character varying"))
    op.alter_column('counter_geometry_properties', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_geometry_properties_geometry_id'), table_name='counter_geometry_properties')
    op.drop_index(op.f('idx_geometry_properties_name'), table_name='counter_geometry_properties')
    op.create_index(op.f('ix_counter_geometry_properties_property_id'), 'counter_geometry_properties', ['property_id'], unique=False)
    op.drop_constraint(op.f('counter_geometry_properties_geometry_id_fkey'), 'counter_geometry_properties', type_='foreignkey')
    op.create_foreign_key(None, 'counter_geometry_properties', 'counter_geometries', ['geometry_id'], ['geometry_id'])
    op.drop_table_comment(
        'counter_geometry_properties',
        existing_comment='柜位几何属性表',
        schema=None
    )
    op.alter_column('counter_groups', 'store_id',
               existing_type=sa.INTEGER(),
               comment='门店ID',
               existing_nullable=False)
    op.alter_column('counter_groups', 'area_code',
               existing_type=sa.VARCHAR(length=20),
               comment='区域编码',
               existing_nullable=True)
    op.alter_column('counter_groups', 'area_name',
               existing_type=sa.VARCHAR(length=100),
               comment='区域名称',
               existing_nullable=True)
    op.alter_column('counter_groups', 'category_code',
               existing_type=sa.VARCHAR(length=20),
               comment='类别编码',
               existing_nullable=True)
    op.alter_column('counter_groups', 'category_name',
               existing_type=sa.VARCHAR(length=100),
               comment='类别名称',
               existing_nullable=True)
    op.alter_column('counters', 'counter_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_comment='柜位编号')
    op.alter_column('counters', 'deposit',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='装修保证金',
               existing_comment='押金',
               existing_nullable=True)
    op.alter_column('counters', 'group_code',
               existing_type=sa.VARCHAR(length=20),
               comment='柜组编码',
               existing_nullable=True)
    op.alter_column('counters', 'facade_image_url',
               existing_type=sa.VARCHAR(length=500),
               comment='门头图片URL',
               existing_nullable=True)
    op.alter_column('counters', 'monthly_revenue',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='POS押金',
               existing_nullable=True)
    op.drop_index(op.f('idx_counters_geometry_id'), table_name='counters')
    op.alter_column('floors', 'building_code',
               existing_type=sa.VARCHAR(length=20),
               comment='栋号编码（如A栋、B栋）',
               existing_nullable=True)
    op.alter_column('floors', 'building_name',
               existing_type=sa.VARCHAR(length=50),
               comment='栋号名称（如A栋、B栋、主楼）',
               existing_nullable=True)
    op.alter_column('floors', 'floor_number',
               existing_type=sa.INTEGER(),
               comment='楼层编号（-1表示负一楼，0表示地面层，1表示一楼）',
               existing_comment='楼层编号',
               existing_nullable=False)
    op.alter_column('floors', 'floor_display_name',
               existing_type=sa.VARCHAR(length=50),
               comment='楼层显示名称（如B1、1F、16F）',
               existing_nullable=True)
    op.alter_column('floors', 'sort_order',
               existing_type=sa.INTEGER(),
               comment='排序顺序（用于楼层列表排序）',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.add_column('revenue_data', sa.Column('group_code', sa.String(length=20), nullable=True, comment='柜组编码'))
    op.alter_column('revenue_data', 'counter_id',
               existing_type=sa.INTEGER(),
               comment='柜位ID',
               existing_nullable=False)
    op.alter_column('revenue_data', 'counter_code',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=True,
               comment='柜位编码')
    op.alter_column('revenue_data', 'counter_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               comment='柜位名称')
    op.alter_column('revenue_data', 'store_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='门店ID')
    op.alter_column('revenue_data', 'store_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               comment='门店名称')
    op.alter_column('revenue_data', 'floor_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='楼层ID')
    op.alter_column('revenue_data', 'floor_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               comment='楼层名称')
    op.alter_column('revenue_data', 'area',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               comment='面积（平方米）')
    op.alter_column('revenue_data', 'x',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               type_=sa.Numeric(precision=10, scale=4),
               nullable=True,
               comment='X坐标')
    op.alter_column('revenue_data', 'y',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               type_=sa.Numeric(precision=10, scale=4),
               nullable=True,
               comment='Y坐标')
    op.alter_column('revenue_data', 'width',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               type_=sa.Numeric(precision=10, scale=4),
               nullable=True,
               comment='宽度')
    op.alter_column('revenue_data', 'height',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               type_=sa.Numeric(precision=10, scale=4),
               nullable=True,
               comment='高度')
    op.alter_column('revenue_data', 'monthly_revenue',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=True,
               comment='月收益')
    op.alter_column('revenue_data', 'daily_revenue',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=True,
               comment='日收益')
    op.alter_column('revenue_data', 'revenue_per_sqm',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               comment='每平米收益')
    op.alter_column('revenue_data', 'revenue_trend',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               nullable=True,
               comment='收益趋势')
    op.alter_column('revenue_data', 'revenue_change_percent',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True,
               comment='收益变化百分比')
    op.alter_column('revenue_data', 'report_date',
               existing_type=sa.DATE(),
               nullable=True,
               comment='报告日期')
    op.alter_column('revenue_data', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               comment='状态')
    op.alter_column('revenue_data', 'tenant_name',
               existing_type=sa.VARCHAR(length=100),
               comment='租户名称',
               existing_nullable=True)
    op.alter_column('revenue_data', 'brand_name',
               existing_type=sa.VARCHAR(length=100),
               comment='品牌名称',
               existing_nullable=True)
    op.alter_column('revenue_data', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='创建时间',
               existing_nullable=True)
    op.alter_column('revenue_data', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='更新时间',
               existing_nullable=True)
    op.drop_index(op.f('idx_revenue_data_date'), table_name='revenue_data')
    op.drop_index(op.f('idx_revenue_data_monthly_revenue'), table_name='revenue_data')
    op.drop_index(op.f('idx_revenue_data_report_date_status'), table_name='revenue_data')
    op.drop_index(op.f('idx_revenue_data_same_period_date'), table_name='revenue_data')
    op.drop_index(op.f('idx_revenue_data_year_month'), table_name='revenue_data')
    op.drop_index(op.f('ix_revenue_data_counter_id'), table_name='revenue_data')
    op.drop_index(op.f('ix_revenue_data_floor_id'), table_name='revenue_data')
    op.drop_index(op.f('ix_revenue_data_report_date'), table_name='revenue_data')
    op.drop_index(op.f('ix_revenue_data_status'), table_name='revenue_data')
    op.drop_index(op.f('ix_revenue_data_store_id'), table_name='revenue_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_revenue_data_store_id'), 'revenue_data', ['store_id'], unique=False)
    op.create_index(op.f('ix_revenue_data_status'), 'revenue_data', ['status'], unique=False)
    op.create_index(op.f('ix_revenue_data_report_date'), 'revenue_data', ['report_date'], unique=False)
    op.create_index(op.f('ix_revenue_data_floor_id'), 'revenue_data', ['floor_id'], unique=False)
    op.create_index(op.f('ix_revenue_data_counter_id'), 'revenue_data', ['counter_id'], unique=False)
    op.create_index(op.f('idx_revenue_data_year_month'), 'revenue_data', ['year', 'month'], unique=False)
    op.create_index(op.f('idx_revenue_data_same_period_date'), 'revenue_data', ['same_period_date'], unique=False)
    op.create_index(op.f('idx_revenue_data_report_date_status'), 'revenue_data', ['report_date', 'status'], unique=False)
    op.create_index(op.f('idx_revenue_data_monthly_revenue'), 'revenue_data', ['monthly_revenue'], unique=False)
    op.create_index(op.f('idx_revenue_data_date'), 'revenue_data', ['date'], unique=False)
    op.alter_column('revenue_data', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True)
    op.alter_column('revenue_data', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('revenue_data', 'brand_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='品牌名称',
               existing_nullable=True)
    op.alter_column('revenue_data', 'tenant_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='租户名称',
               existing_nullable=True)
    op.alter_column('revenue_data', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               comment=None,
               existing_comment='状态')
    op.alter_column('revenue_data', 'report_date',
               existing_type=sa.DATE(),
               nullable=False,
               comment=None,
               existing_comment='报告日期')
    op.alter_column('revenue_data', 'revenue_change_percent',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False,
               comment=None,
               existing_comment='收益变化百分比')
    op.alter_column('revenue_data', 'revenue_trend',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               nullable=False,
               comment=None,
               existing_comment='收益趋势')
    op.alter_column('revenue_data', 'revenue_per_sqm',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               comment=None,
               existing_comment='每平米收益')
    op.alter_column('revenue_data', 'daily_revenue',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               comment=None,
               existing_comment='日收益')
    op.alter_column('revenue_data', 'monthly_revenue',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               comment=None,
               existing_comment='月收益')
    op.alter_column('revenue_data', 'height',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.NUMERIC(precision=8, scale=4),
               nullable=False,
               comment=None,
               existing_comment='高度')
    op.alter_column('revenue_data', 'width',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.NUMERIC(precision=8, scale=4),
               nullable=False,
               comment=None,
               existing_comment='宽度')
    op.alter_column('revenue_data', 'y',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.NUMERIC(precision=8, scale=4),
               nullable=False,
               comment=None,
               existing_comment='Y坐标')
    op.alter_column('revenue_data', 'x',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.NUMERIC(precision=8, scale=4),
               nullable=False,
               comment=None,
               existing_comment='X坐标')
    op.alter_column('revenue_data', 'area',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               comment=None,
               existing_comment='面积（平方米）')
    op.alter_column('revenue_data', 'floor_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               comment=None,
               existing_comment='楼层名称')
    op.alter_column('revenue_data', 'floor_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='楼层ID')
    op.alter_column('revenue_data', 'store_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               comment=None,
               existing_comment='门店名称')
    op.alter_column('revenue_data', 'store_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='门店ID')
    op.alter_column('revenue_data', 'counter_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               comment=None,
               existing_comment='柜位名称')
    op.alter_column('revenue_data', 'counter_code',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=False,
               comment=None,
               existing_comment='柜位编码')
    op.alter_column('revenue_data', 'counter_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='柜位ID',
               existing_nullable=False)
    op.drop_column('revenue_data', 'group_code')
    op.alter_column('floors', 'sort_order',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='排序顺序（用于楼层列表排序）',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('floors', 'floor_display_name',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='楼层显示名称（如B1、1F、16F）',
               existing_nullable=True)
    op.alter_column('floors', 'floor_number',
               existing_type=sa.INTEGER(),
               comment='楼层编号',
               existing_comment='楼层编号（-1表示负一楼，0表示地面层，1表示一楼）',
               existing_nullable=False)
    op.alter_column('floors', 'building_name',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='栋号名称（如A栋、B栋、主楼）',
               existing_nullable=True)
    op.alter_column('floors', 'building_code',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='栋号编码（如A栋、B栋）',
               existing_nullable=True)
    op.create_index(op.f('idx_counters_geometry_id'), 'counters', ['geometry_id'], unique=False)
    op.alter_column('counters', 'monthly_revenue',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='POS押金',
               existing_nullable=True)
    op.alter_column('counters', 'facade_image_url',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='门头图片URL',
               existing_nullable=True)
    op.alter_column('counters', 'group_code',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='柜组编码',
               existing_nullable=True)
    op.alter_column('counters', 'deposit',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='押金',
               existing_comment='装修保证金',
               existing_nullable=True)
    op.alter_column('counters', 'counter_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_comment='柜位编号')
    op.alter_column('counter_groups', 'category_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='类别名称',
               existing_nullable=True)
    op.alter_column('counter_groups', 'category_code',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='类别编码',
               existing_nullable=True)
    op.alter_column('counter_groups', 'area_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='区域名称',
               existing_nullable=True)
    op.alter_column('counter_groups', 'area_code',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='区域编码',
               existing_nullable=True)
    op.alter_column('counter_groups', 'store_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='门店ID',
               existing_nullable=False)
    op.create_table_comment(
        'counter_geometry_properties',
        '柜位几何属性表',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'counter_geometry_properties', type_='foreignkey')
    op.create_foreign_key(op.f('counter_geometry_properties_geometry_id_fkey'), 'counter_geometry_properties', 'counter_geometries', ['geometry_id'], ['geometry_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_counter_geometry_properties_property_id'), table_name='counter_geometry_properties')
    op.create_index(op.f('idx_geometry_properties_name'), 'counter_geometry_properties', ['property_name'], unique=False)
    op.create_index(op.f('idx_geometry_properties_geometry_id'), 'counter_geometry_properties', ['geometry_id'], unique=False)
    op.alter_column('counter_geometry_properties', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('counter_geometry_properties', 'property_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='属性类型：string, number, boolean, json',
               existing_nullable=True,
               existing_server_default=sa.text("'string'::character varying"))
    op.alter_column('counter_geometry_properties', 'property_value',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='属性值（JSON格式）',
               existing_nullable=True)
    op.alter_column('counter_geometry_properties', 'property_name',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='属性名',
               existing_nullable=False)
    op.alter_column('counter_geometry_properties', 'property_id',
               existing_type=sa.INTEGER(),
               comment='属性ID',
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'counter_geometries',
        '柜位几何信息表',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'counter_geometries', type_='foreignkey')
    op.create_foreign_key(op.f('counter_geometries_counter_id_fkey'), 'counter_geometries', 'counters', ['counter_id'], ['counter_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_counter_geometries_geometry_id'), table_name='counter_geometries')
    op.create_unique_constraint(op.f('unique_counter_geometry'), 'counter_geometries', ['counter_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_counter_geometries_shape_type'), 'counter_geometries', ['shape_type'], unique=False)
    op.create_index(op.f('idx_counter_geometries_counter_id'), 'counter_geometries', ['counter_id'], unique=False)
    op.create_index(op.f('idx_counter_geometries_bounding_box'), 'counter_geometries', ['bounding_box_min_x', 'bounding_box_min_y', 'bounding_box_max_x', 'bounding_box_max_y'], unique=False)
    op.alter_column('counter_geometries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('counter_geometries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('counter_geometries', 'bounding_box_max_y',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='边界框最大Y坐标',
               existing_nullable=True)
    op.alter_column('counter_geometries', 'bounding_box_max_x',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='边界框最大X坐标',
               existing_nullable=True)
    op.alter_column('counter_geometries', 'bounding_box_min_y',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='边界框最小Y坐标',
               existing_nullable=True)
    op.alter_column('counter_geometries', 'bounding_box_min_x',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='边界框最小X坐标',
               existing_nullable=True)
    op.alter_column('counter_geometries', 'ellipse_rotation',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment=None,
               existing_comment='椭圆旋转角度',
               existing_nullable=True)
    op.alter_column('counter_geometries', 'ellipse_radius_y',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='椭圆Y轴半径',
               existing_nullable=True)
    op.alter_column('counter_geometries', 'ellipse_radius_x',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='椭圆X轴半径',
               existing_nullable=True)
    op.alter_column('counter_geometries', 'ellipse_center_y',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='椭圆中心Y坐标',
               existing_nullable=True)
    op.alter_column('counter_geometries', 'ellipse_center_x',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='椭圆中心X坐标',
               existing_nullable=True)
    op.alter_column('counter_geometries', 'radius',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='半径',
               existing_nullable=True)
    op.alter_column('counter_geometries', 'center_y',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='圆心Y坐标',
               existing_nullable=True)
    op.alter_column('counter_geometries', 'center_x',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='圆心X坐标',
               existing_nullable=True)
    op.alter_column('counter_geometries', 'polygon_coordinates',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='多边形坐标点，JSON格式：[[x1,y1],[x2,y2],...]',
               existing_nullable=True)
    op.alter_column('counter_geometries', 'rotation',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment=None,
               existing_comment='旋转角度',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('counter_geometries', 'height',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='高度（矩形）',
               existing_nullable=True)
    op.alter_column('counter_geometries', 'width',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='宽度（矩形）',
               existing_nullable=True)
    op.alter_column('counter_geometries', 'position_y',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Y坐标（矩形）',
               existing_nullable=True)
    op.alter_column('counter_geometries', 'position_x',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='X坐标（矩形）',
               existing_nullable=True)
    op.alter_column('counter_geometries', 'geometry_id',
               existing_type=sa.INTEGER(),
               comment='几何信息ID',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('counter_geometries_geometry_id_seq'::regclass)"))
    op.create_table('revenue_summary',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('floor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('report_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('total_revenue', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('monthly_revenue', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('daily_revenue', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('average_revenue_per_sqm', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('total_counters', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('active_counters', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('revenue_growth_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('revenue_summary_pkey'))
    )
    op.create_index(op.f('ix_revenue_summary_store_id'), 'revenue_summary', ['store_id'], unique=False)
    op.create_index(op.f('ix_revenue_summary_report_date'), 'revenue_summary', ['report_date'], unique=False)
    op.create_index(op.f('ix_revenue_summary_id'), 'revenue_summary', ['id'], unique=False)
    op.create_index(op.f('ix_revenue_summary_floor_id'), 'revenue_summary', ['floor_id'], unique=False)
    op.create_index(op.f('idx_revenue_summary_unique'), 'revenue_summary', ['store_id', 'floor_id', 'report_date'], unique=True)
    op.create_table('ODS_SALEGOODSLIST',
    sa.Column('SGLDATE', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('SGLTPID', sa.CHAR(length=2), autoincrement=False, nullable=False),
    sa.Column('SGLSUMMARY', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('SGLMARKET', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('SGLMFID', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('SGLGDID', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('SGLBARCODE', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('SGLGDTYPE', sa.CHAR(length=1), autoincrement=False, nullable=False),
    sa.Column('SGLCATID', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('SGLTAXTYPE', sa.CHAR(length=1), autoincrement=False, nullable=False),
    sa.Column('SGLXSTAX', sa.NUMERIC(precision=8, scale=4), autoincrement=False, nullable=False),
    sa.Column('SGLXFTAX', sa.NUMERIC(precision=8, scale=4), autoincrement=False, nullable=False),
    sa.Column('SGLPPCODE', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('SGLUID', sa.VARCHAR(length=6), autoincrement=False, nullable=False),
    sa.Column('SGLHSRQ', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('SGLBATCHNO', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('SGLSUPID', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('SGLANALCODE', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('SGLSJ', sa.NUMERIC(precision=16, scale=4), autoincrement=False, nullable=False),
    sa.Column('SGLKL', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=False),
    sa.Column('SGLJS', sa.NUMERIC(precision=16, scale=4), autoincrement=False, nullable=False),
    sa.Column('SGLSL', sa.NUMERIC(precision=16, scale=4), autoincrement=False, nullable=False),
    sa.Column('SGLSJJE', sa.NUMERIC(precision=16, scale=4), autoincrement=False, nullable=False),
    sa.Column('SGLXSSR', sa.NUMERIC(precision=16, scale=4), autoincrement=False, nullable=False),
    sa.Column('SGLXSSE', sa.NUMERIC(precision=16, scale=4), autoincrement=False, nullable=False),
    sa.Column('SGLXFSE', sa.NUMERIC(precision=16, scale=4), autoincrement=False, nullable=False),
    sa.Column('SGLQTSR', sa.NUMERIC(precision=16, scale=4), autoincrement=False, nullable=False),
    sa.Column('SGLSYSY', sa.NUMERIC(precision=16, scale=4), autoincrement=False, nullable=False),
    sa.Column('SGLPOPSR', sa.NUMERIC(precision=16, scale=4), autoincrement=False, nullable=False),
    sa.Column('SGLCUSTSR', sa.NUMERIC(precision=16, scale=4), autoincrement=False, nullable=False),
    sa.Column('SGLFCDSR', sa.NUMERIC(precision=16, scale=4), autoincrement=False, nullable=False),
    sa.Column('SGLPFSR', sa.NUMERIC(precision=16, scale=4), autoincrement=False, nullable=False),
    sa.Column('SGLYXSSR', sa.NUMERIC(precision=16, scale=4), autoincrement=False, nullable=False),
    sa.Column('SGLTOTZK', sa.NUMERIC(precision=16, scale=4), autoincrement=False, nullable=False),
    sa.Column('SGLSUPZK', sa.NUMERIC(precision=16, scale=4), autoincrement=False, nullable=False),
    sa.Column('SGLPOPZK', sa.NUMERIC(precision=16, scale=4), autoincrement=False, nullable=False),
    sa.Column('SGLCUSTZK', sa.NUMERIC(precision=16, scale=4), autoincrement=False, nullable=False),
    sa.Column('SGLFCDZK', sa.NUMERIC(precision=16, scale=4), autoincrement=False, nullable=False),
    sa.Column('SGLPFZK', sa.NUMERIC(precision=16, scale=4), autoincrement=False, nullable=False),
    sa.Column('SGLGRANTZK', sa.NUMERIC(precision=16, scale=4), autoincrement=False, nullable=False),
    sa.Column('SGLYJHX', sa.NUMERIC(precision=16, scale=4), autoincrement=False, nullable=False),
    sa.Column('SGLZSZK', sa.NUMERIC(precision=16, scale=4), autoincrement=False, nullable=False),
    sa.Column('SGLTHSS', sa.NUMERIC(precision=16, scale=4), autoincrement=False, nullable=False),
    sa.Column('SGLADJUSTZK', sa.NUMERIC(precision=16, scale=4), autoincrement=False, nullable=False),
    sa.Column('SGLCASH', sa.NUMERIC(precision=16, scale=4), autoincrement=False, nullable=False),
    sa.Column('SGLCHECK', sa.NUMERIC(precision=16, scale=4), autoincrement=False, nullable=False),
    sa.Column('SGLCCARD', sa.NUMERIC(precision=16, scale=4), autoincrement=False, nullable=False),
    sa.Column('SGLFCARD', sa.NUMERIC(precision=16, scale=4), autoincrement=False, nullable=False),
    sa.Column('SGLGCERT', sa.NUMERIC(precision=16, scale=4), autoincrement=False, nullable=False),
    sa.Column('SGLGZJE', sa.NUMERIC(precision=16, scale=4), autoincrement=False, nullable=False),
    sa.Column('SGLOPAY', sa.NUMERIC(precision=16, scale=4), autoincrement=False, nullable=False),
    sa.Column('SGLTIMES', sa.NUMERIC(precision=16, scale=4), autoincrement=False, nullable=True),
    sa.Column('SGLN1', sa.NUMERIC(precision=16, scale=4), autoincrement=False, nullable=True),
    sa.Column('SGLN2', sa.NUMERIC(precision=16, scale=4), autoincrement=False, nullable=True),
    sa.Column('SGLN3', sa.NUMERIC(precision=16, scale=4), autoincrement=False, nullable=True),
    sa.Column('SGLN4', sa.NUMERIC(precision=16, scale=4), autoincrement=False, nullable=True),
    sa.Column('SGLN5', sa.NUMERIC(precision=16, scale=4), autoincrement=False, nullable=True),
    sa.Column('SGLVC1', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('SGLVC2', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('SGLVC3', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('SGLWMID', sa.CHAR(length=1), autoincrement=False, nullable=False),
    sa.Column('SGLFQJE', sa.NUMERIC(precision=16, scale=4), autoincrement=False, nullable=True),
    sa.Column('SGLSQJE', sa.NUMERIC(precision=16, scale=4), autoincrement=False, nullable=True),
    sa.Column('SGLQXSSR', sa.NUMERIC(precision=16, scale=4), autoincrement=False, nullable=True),
    sa.Column('SGLN6', sa.NUMERIC(precision=16, scale=4), autoincrement=False, nullable=True),
    sa.Column('SGLN7', sa.NUMERIC(precision=16, scale=4), autoincrement=False, nullable=True),
    sa.Column('SGLN8', sa.NUMERIC(precision=16, scale=4), autoincrement=False, nullable=True),
    sa.Column('SGLN9', sa.NUMERIC(precision=16, scale=4), autoincrement=False, nullable=True),
    sa.Column('SGLN10', sa.NUMERIC(precision=16, scale=4), autoincrement=False, nullable=True),
    sa.Column('SGLXYKSR1', sa.NUMERIC(precision=16, scale=4), autoincrement=False, nullable=True),
    sa.Column('SGLXYKSR2', sa.NUMERIC(precision=16, scale=4), autoincrement=False, nullable=True),
    sa.Column('SGLXYKSR3', sa.NUMERIC(precision=16, scale=4), autoincrement=False, nullable=True),
    sa.Column('SGLXYKSR4', sa.NUMERIC(precision=16, scale=4), autoincrement=False, nullable=True),
    sa.Column('SGLXYKSR5', sa.NUMERIC(precision=16, scale=4), autoincrement=False, nullable=True),
    sa.Column('SGLXYKSR6', sa.NUMERIC(precision=16, scale=4), autoincrement=False, nullable=True),
    sa.Column('SGLXYKSR7', sa.NUMERIC(precision=16, scale=4), autoincrement=False, nullable=True),
    sa.Column('SGLXYKSR8', sa.NUMERIC(precision=16, scale=4), autoincrement=False, nullable=True),
    sa.Column('SGLXYKSR9', sa.NUMERIC(precision=16, scale=4), autoincrement=False, nullable=True),
    sa.Column('SGLXYKSR10', sa.NUMERIC(precision=16, scale=4), autoincrement=False, nullable=True),
    sa.Column('SGLBILLNO', sa.NUMERIC(precision=1000, scale=53), autoincrement=False, nullable=False),
    sa.Column('SGLROWNO', sa.NUMERIC(precision=1000, scale=53), autoincrement=False, nullable=False),
    sa.Column('SGLBASEKL', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=True),
    sa.Column('SGLN11', sa.NUMERIC(precision=1000, scale=53), autoincrement=False, nullable=True),
    sa.Column('SGLN12', sa.NUMERIC(precision=1000, scale=53), autoincrement=False, nullable=True),
    sa.Column('SGLN13', sa.NUMERIC(precision=1000, scale=53), autoincrement=False, nullable=True),
    sa.Column('SGLN14', sa.NUMERIC(precision=1000, scale=53), autoincrement=False, nullable=True),
    sa.Column('SGLN15', sa.NUMERIC(precision=1000, scale=53), autoincrement=False, nullable=True),
    sa.Column('SGLN16', sa.NUMERIC(precision=1000, scale=53), autoincrement=False, nullable=True),
    sa.Column('SGLN17', sa.NUMERIC(precision=1000, scale=53), autoincrement=False, nullable=True),
    sa.Column('SGLN18', sa.NUMERIC(precision=1000, scale=53), autoincrement=False, nullable=True),
    sa.Column('SGLN19', sa.NUMERIC(precision=1000, scale=53), autoincrement=False, nullable=True),
    sa.Column('SGLN20', sa.NUMERIC(precision=1000, scale=53), autoincrement=False, nullable=True),
    sa.Column('SGLN21', sa.NUMERIC(precision=1000, scale=53), autoincrement=False, nullable=True),
    sa.Column('SGLN22', sa.NUMERIC(precision=1000, scale=53), autoincrement=False, nullable=True),
    sa.Column('SGLN23', sa.NUMERIC(precision=1000, scale=53), autoincrement=False, nullable=True),
    sa.Column('SGLN24', sa.NUMERIC(precision=1000, scale=53), autoincrement=False, nullable=True),
    sa.Column('SGLN25', sa.NUMERIC(precision=1000, scale=53), autoincrement=False, nullable=True),
    sa.Column('SGLVC4', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('SGLVC5', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('SGLVC6', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('SGLVC7', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('SGLVC8', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('SGLVC9', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('SGLVC10', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('SGLVC11', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('SGLVC12', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('SGLVC13', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('SGLVC14', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('SGLVC15', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('SGLSALEDATE', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('SGLNETML', sa.NUMERIC(precision=1000, scale=53), autoincrement=False, nullable=True),
    sa.Column('SGLCARDTYPE', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('SGLSYJID', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('SGLINVNO', sa.NUMERIC(precision=1000, scale=53), autoincrement=False, nullable=True),
    sa.Column('SGLCHECKER', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('SGLPOSCLS', sa.CHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('SGLSHDATE', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('SGLTMTYPE', sa.CHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('SGLMD', sa.CHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('SGLFYSL', sa.NUMERIC(precision=16, scale=4), autoincrement=False, nullable=True),
    sa.Column('SGLVIP1SR', sa.NUMERIC(precision=16, scale=4), autoincrement=False, nullable=True),
    sa.Column('SGLVIP2SR', sa.NUMERIC(precision=16, scale=4), autoincrement=False, nullable=True),
    sa.Column('SGLVIP3SR', sa.NUMERIC(precision=16, scale=4), autoincrement=False, nullable=True),
    sa.Column('SGLVIP4SR', sa.NUMERIC(precision=16, scale=4), autoincrement=False, nullable=True),
    sa.Column('SGLVIP5SR', sa.NUMERIC(precision=16, scale=4), autoincrement=False, nullable=True),
    sa.Column('SGLXYKFY1', sa.NUMERIC(precision=1000, scale=53), autoincrement=False, nullable=True),
    sa.Column('SGLXYKFY2', sa.NUMERIC(precision=1000, scale=53), autoincrement=False, nullable=True),
    sa.Column('SGLXYKFY3', sa.NUMERIC(precision=1000, scale=53), autoincrement=False, nullable=True),
    sa.Column('SGLXYKFY4', sa.NUMERIC(precision=1000, scale=53), autoincrement=False, nullable=True),
    sa.Column('SGLXYKFY5', sa.NUMERIC(precision=1000, scale=53), autoincrement=False, nullable=True),
    sa.Column('SGLXYKFY6', sa.NUMERIC(precision=1000, scale=53), autoincrement=False, nullable=True),
    sa.Column('SGLXYKFY7', sa.NUMERIC(precision=1000, scale=53), autoincrement=False, nullable=True),
    sa.Column('SGLXYKFY8', sa.NUMERIC(precision=1000, scale=53), autoincrement=False, nullable=True),
    sa.Column('SGLXYKFY9', sa.NUMERIC(precision=1000, scale=53), autoincrement=False, nullable=True),
    sa.Column('SGLXYKFY10', sa.NUMERIC(precision=1000, scale=53), autoincrement=False, nullable=True),
    sa.Column('SGLSPSX', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('SGLJJTAX', sa.NUMERIC(precision=8, scale=4), autoincrement=False, nullable=True),
    sa.Column('SGLN26', sa.NUMERIC(precision=1000, scale=53), autoincrement=False, nullable=True),
    sa.Column('SGLN27', sa.NUMERIC(precision=1000, scale=53), autoincrement=False, nullable=True),
    sa.Column('SGLN28', sa.NUMERIC(precision=1000, scale=53), autoincrement=False, nullable=True),
    sa.Column('SGLN29', sa.NUMERIC(precision=1000, scale=53), autoincrement=False, nullable=True)
    )
    op.create_table('BH_DW_TIME_DIM',
    sa.Column('DIM_YEAR', sa.NUMERIC(precision=1000, scale=53), autoincrement=False, nullable=True),
    sa.Column('DIM_QUARTER', sa.NUMERIC(precision=1000, scale=53), autoincrement=False, nullable=True),
    sa.Column('DIM_MONTH', sa.NUMERIC(precision=1000, scale=53), autoincrement=False, nullable=True),
    sa.Column('DIM_FINANCE_MONTH', sa.NUMERIC(precision=1000, scale=53), autoincrement=False, nullable=True),
    sa.Column('DIM_FINANCE_MONTH_MM', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('DIM_FINANCE_DAYS', sa.NUMERIC(precision=1000, scale=53), autoincrement=False, nullable=True),
    sa.Column('DIM_WEEK', sa.NUMERIC(precision=1000, scale=53), autoincrement=False, nullable=True),
    sa.Column('NATURAL_WEEK', sa.NUMERIC(precision=1000, scale=53), autoincrement=False, nullable=True),
    sa.Column('DIM_WEEKDAY', sa.NUMERIC(precision=1000, scale=53), autoincrement=False, nullable=True),
    sa.Column('WEEK_RANK', sa.NUMERIC(precision=1000, scale=53), autoincrement=False, nullable=True),
    sa.Column('DIM_DATE', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('DIM_FINANCE_MONTH_END', sa.NUMERIC(precision=1000, scale=53), autoincrement=False, nullable=True),
    sa.Column('BEGINNING_YEAR', sa.VARCHAR(length=4), autoincrement=False, nullable=True),
    sa.Column('DIM_FINANCE_MONTH_PREVIOUS', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('DEPART_STORE_WEEK', sa.NUMERIC(precision=1000, scale=53), autoincrement=False, nullable=True),
    sa.Column('DEPART_STORE_WEEK2', sa.NUMERIC(precision=1000, scale=53), autoincrement=False, nullable=True),
    sa.Column('DIM_FINANCE_MONTH2', sa.NUMERIC(precision=1000, scale=53), autoincrement=False, nullable=True),
    sa.Column('DIM_FINANCE_MONTH2_MM', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('LOAD_DATE', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('DIM_FINANCE_MONTH_FJ', sa.NUMERIC(precision=1000, scale=53), autoincrement=False, nullable=True),
    sa.Column('DIM_MONTH_MM', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('DIM_DATE', name=op.f('SYS_C0013798'))
    )
    op.create_table('revenue_trends',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('counter_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('trend_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('revenue_7d_avg', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('revenue_30d_avg', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('revenue_90d_avg', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('trend_direction', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('trend_strength', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('revenue_trends_pkey'))
    )
    op.create_index(op.f('ix_revenue_trends_trend_date'), 'revenue_trends', ['trend_date'], unique=False)
    op.create_index(op.f('ix_revenue_trends_id'), 'revenue_trends', ['id'], unique=False)
    op.create_index(op.f('ix_revenue_trends_counter_id'), 'revenue_trends', ['counter_id'], unique=False)
    op.create_index(op.f('idx_revenue_trends_unique'), 'revenue_trends', ['counter_id', 'trend_date'], unique=True)
    # ### end Alembic commands ###
