"""Add hall management tables for counter management system

Revision ID: 861c1ad607a5
Revises: 7054b51d8eb8
Create Date: 2025-09-02 14:17:44.935452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '861c1ad607a5'
down_revision: Union[str, Sequence[str], None] = '7054b51d8eb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('floors', sa.Column('floor_plan_data', sa.JSON(), nullable=True, comment='平面图元数据'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('floors', 'floor_plan_data')
    # ### end Alembic commands ###
